name: Ping Rocket Verify

on:
  schedule:
    - cron: '*/2 * * * *'  # Every 2 minutes
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Ping to Rocket Verify with Retry and JSON Check
        run: |
          echo "🔄 Pinging Rocket Verify health endpoint with retry logic and JSON status check..."

          RETRIES=3
          DELAY=5
          URL="https://rocketverify.onrender.com/health"

          for i in $(seq 1 $RETRIES); do
            RESPONSE=$(curl -s "$URL")
            STATUS_CODE=$(echo "$RESPONSE" | jq -r '.status' 2>/dev/null)

            if [ "$STATUS_CODE" == "ok" ]; then
              echo "✅ Rocket Verify is healthy (status: $STATUS_CODE)"
              exit 0
            else
              echo "❌ Attempt $i failed. Status: $STATUS_CODE. Retrying in ${DELAY}s..."
              sleep $DELAY
            fi
          done

          echo "::error::🚨 Rocket Verify failed after $RETRIES attempts. Last status: $STATUS_CODE"
          exit 1

      - name: Install jq (if not present)
        run: sudo apt-get update && sudo apt-get install -y jq