name: Ping Load Balancer

on:
  schedule:
    - cron: '*/2 * * * *'  # Every 5 minutes
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Ping to Load Balancer
        run: |
          echo "Pinging rockets-nfcf load balancer..."
          curl -s -o /dev/null -w "%{http_code}" https://rockets-nfcf.onrender.com/health | tee result.txt

          STATUS_CODE=$(cat result.txt)

          if [ "$STATUS_CODE" -ne 200 ]; then
            echo "::error::🚨 Load balancer not responding correctly. Status code: $STATUS_CODE"
            exit 1
          else
            echo "✅ Load balancer is healthy (HTTP $STATUS_CODE)"
          fi